# Generated by Django 3.2.19 on 2024-03-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_uploaded_un'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded',
            name='date',
            field=models.CharField(default='1970-01-01 00:00:00', max_length=100),
        ),
        migrations.AddField(
            model_name='uploaded',
            name='title',
            field=models.CharField(default='1970-01-01 00:00:00', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='date',
            field=models.CharField(default='1970-01-01 00:00:00', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(default='1970-01-01 00:00:00', max_length=100),
        ),
    ]
