# Generated by Django 3.2.19 on 2024-03-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20240315_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded',
            name='un',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
