# Generated by Django 3.2.19 on 2024-03-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='imageimage',
        ),
    ]
